version: "3.8"

services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    ports:
      - "5001:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: >
      mlflow server \
      --backend-store-uri sqlite:///mlflow.db \
      --default-artifact-root /mlflow/mlruns \
      --host 0.0.0.0